### PR TITLE
Changing OFPP_FLOOD to OFPP_ALL

### PR DESCRIPTION
**Pull request by samrussell**
I'm not sure what discussion has been had around this, but the OpenFlow spec has FLOOD as optional, but ALL as mandatory, it sounds like there's some STP stuff around it, but this seems like a better choice

http://www.openflow.org/documents/openflow-spec-v1.0.0.pdf Page 6 has the details

### CODE REVIEW

**Comment by MurphyMc** [comment]
It's a valid point that FLOOD is optional and ALL is mandatory.  I actually don't know how widely FLOOD is not implemented.
- I'm willing to take the switch to ALL for l2_learning_tutorial.
- For ofcommand, I'm not sure how much sense it makes to do this for the FloodPacketCommand.  I'm also not sure how much use ofcommand gets.
- I don't think I'm willing to accept it wholesale for l2_multi and l2_learning.

I don't want to take it for l2_learning and l2_multi because people do actually use these demos on topologies with loops, and using FLOOD means that this actually works when you enable the spanning_tree component and have switches with settable flood bits (which includes at least the very common scenarios with Mininet and OVS -- the spec oversells the importance of actual STP here).  It also means they'll work correctly on loopy topologies with hybrid switches that actually do STP.  This seems to leave us with three options:
- Leave them how they are (do we have any reports of these actually being problematic?)
- Make FLOOD/ALL an option with a commandline switch
- Try to autodetect when FLOOD is and isn't possible

I actually don't think there's an elegant way to do the last option, but it's hard to say -- the spec seems pretty fuzzy to me here.  And if the spec seems fuzzy, then it seems pretty certain that you can't reliably do it anyway.  The 1.1 spec offers no help here, because it's substantially different (port groups, etc.).

That leaves us with making it a commandline switch or leaving it how it is.

Anyone?

**Comment by tootoonchian** [comment]
I personally think we should leave it the way it is unless someone has a problem with it. The issue of handling optional/mandatory features is a bit tricky for us to correctly appropriately for now.

**Comment by samrussell** [comment]
Good points - I spent a bit of time using the old pyswitch with a single switch, haven't done anything with groups and STP yet. It generally looks like OFPP_FLOOD is aliased to OFPP_ALL for dumb switches, but this isn't guaranteed by the spec.

I'm happy for this pull to not go ahead, but there should be a variation of FloodPacketCommand in ofcommand (either with argument or a new function). If nothing else, would it be worthwhile adding a comment when OFPP_FLOOD is used so that users can see at a glance if they're surprised when some ports aren't used by FLOOD.

I just put this forward for purity. It fits the standard better, and I personally think that OpenFlow should be obseleting STP and other layer-2 loop-prevention protocols. Relying on them for examples may be useful, but FLOOD should really only be used as often as SWITCH in my opinion :)

**Comment by MurphyMc** [comment]
STP doesn't necessarily factor into it even as it is, though the spec says/implies that it does in a way that I think it shouldn't.

The POX spanning_tree module doesn't use STP at all.  It has nothing to do with STP except that both of them more or less do the same thing (find a spanning tree; make loops okay).  It finds a spanning tree entirely in the controller in an entirely OpenFlow way.  Once it has figured out the tree, it takes advantage of the fact that at least on some switches (e.g., OVS), you can manually set the OFPPC_NO_FLOOD bit on the port.  That way, we can FLOOD to send to just the spanning tree we've calculated.  An alternative would be to not use FLOOD but instead to install rules with a bunch of output actions (one for each port on the tree), but doing it this way is kind of annoying.

OpenFlow 1.1, IIRC, ditches this idea and just has port groups.  This is actually not as easy as OFPPC_NO_FLOOD for the usecase in question, but it's much more flexible (and it's nicer than having a bunch of multiple-output rules).

All that aside; yeah, let's not pull this.  I propose:
- Add comments in l2_learning and l2_multi near OFPP_FLOOD usage.  Maybe something along the lines of "Use OFPP_FLOOD instead of OFPP_ALL here so that, e.g., spanning_tree will work".
- Do the opposite in l2_learning_tutorial.  Switch to OFPP_ALL, and put in a comment about how OFPP_FLOOD would be useful for topologies with loops.

**Comment by samrussell** [comment]
Thanks, I'm showing my ignorance on how flooding is done in OF ;)

+1 for your proposal

**Comment by MurphyMc** [comment]
Not going to pull, so I've closed this, but opened a corresponding issue that starts with the proposed remedy.

Thanks for bringing this up, samrussell.

**Pull request closed without merging**
