### PR TITLE
Fixing exception caused by "Broken Pipe"

### PR DESCRIPTION
**Pull request by hrsht**
Fixing EBADF file descriptor bug causing pox to stop working, which crops up if an erroneous remote host hangs up the connection during a send. The fix checks if all the stored connections are still active before operating on them and removes the disconnected connection.

See detail on the logs generated by the bug at: https://groups.google.com/group/nox_dev/browse_thread/thread/7e0d7193524e4107

### CODE REVIEW

**Comment by MurphyMc** [comment]
I hesitate to merge this, because I think it may be treating the symptom and not the cause.  Unfortunately, I haven't had much luck finding the cause because I am having trouble reproducing the problem.  Do you have any tips on how I can reproduce this?

**Comment by hrsht** [comment]
My guess is this was caused by a "faulty" client, probably on the VM or the switch code (independent of POX) we were using. This was on VMs run in Amazon's EC2 datacenters. A typical behavior of such bad connections was that the client would connect to the POX controller, the controller would send the Hello message, and the client responds with some garbage and then hangs up the connection, which caused the second send disconnect the connection and a later read of anything about the socket (in this case the file descriptor of the socket) crash POX with the EBADF error message.

I don't think POX can do much if the other side unexpectedly hangs up. This patch very much fixed the issue for us and most importantly didn't interfere with the working of the controller with connections to sane clients/switches.

**Comment by MurphyMc** [comment]
Okay, it looks like Connection.disconnect() is just plain wrong and I think that's the real source of this bug.  Specifically, I think there should always be a call to shutdown(), but not always a call to close(), relying on the Select() loop to get close() called at a later time.

I'll continue looking at this.

**Comment by MurphyMc** [comment]
Here's a quick stab at a proper fix:
https://gist.github.com/2929386

I'd appreciate feedback!

(NOTE: I've deleted the gist, because it has been pushed to the master branch; see below.)

**Comment by MurphyMc** [comment]
My patch seems to have done the trick for resolving issue #20 (which I think is the same as this) and for a poster on the pox-dev mailing list, so I'm pushing it and closing this issue.

**Pull request closed without merging**
